### PR TITLE
  feature/7812-table-column-dropdown-state

### PR DESCRIPTION
**Pull request by pxzdev**

### CODE REVIEW

**Comment by richardhealy** [comment]
All good, just missing this point mentioned in the ticket:

`Also, clicking the sort menu when it is set to ASC, should flip the sort to DESC.`

**Comment by pxzdev** [comment]
@richardhealy I added this feature

**Comment by richardhealy** [comment]
> @richardhealy I added this feature

I can't get it to work in the branch?

**Comment by pxzdev** [comment]
@richardhealy merged with the latest master

**Pull request merged**
