### PR TITLE
Feature/7147 settings page general settings

### PR DESCRIPTION
**Pull request by pxzdev**
https://www.figma.com/file/QpFY9iyQdpAYAekfKDuCcf/Settings-Prototype?node-id=2%3A2406

**Tasks:**
- Page Route: `/settings/general`
- Nav: Setup > General Settings
- Design Settings UI Schema that constructs this page. Add to file in `src/components/SettingsForm/testSchema/` folder

### CODE REVIEW

**Comment by richardhealy** [comment]
The brand tabs should all have the same content. Currently brand 2 and 3 have the default email content: 

Screenshot 2020-02-17 at 10 52 25

Screenshot 2020-02-17 at 10 52 09

**Comment by richardhealy** [comment]
There's a mistake in the design (in Figma). This button should say "add extension".

Screenshot 2020-02-17 at 10 54 40

**Comment by pxzdev** [comment]
> The brand tabs should all have the same content. Currently brand 2 and 3 have the default email content:
> 
> Screenshot 2020-02-17 at 10 52 25
> 
> Screenshot 2020-02-17 at 10 52 09

@richardhealy 
Resolved the brand content issue.

**Comment by pxzdev** [comment]
> There's a mistake in the design (in Figma). This button should say "add extension".
> 
> Screenshot 2020-02-17 at 10 54 40

Resolved text button to `Add Extension`

**Comment by richardhealy** [comment]
Padding seems a little off: 

Screenshot 2020-02-17 at 17 45 48

Screenshot 2020-02-17 at 17 46 00

**Comment by pxzdev** [comment]
> Padding seems a little off:
> 
> Screenshot 2020-02-17 at 17 45 48
> 
> Screenshot 2020-02-17 at 17 46 00

Hi Richard,
I'm updated the pull request.

**Comment by richardhealy** [comment]
Are the brand panels hooked up to the jsonSchema? They see to lose their values?

I can see a `brandX_default_email_account` values and validation but I can't see any other brand values?

**Comment by pxzdev** [comment]
> Are the brand panels hooked up to the jsonSchema? They see to lose their values?
> 
> I can see a `brandX_default_email_account` values and validation but I can't see any other brand values?

Updated values and validation for other brand fields.

**Comment by pxzdev** [comment]
@yegor92 Resolved all of the issues.

**Pull request merged**
