### PR TITLE
Fix/8039 settings forms visual bugs

### PR DESCRIPTION
**Pull request by alex-mazuruk**

### CODE REVIEW

**Comment by alex-mazuruk** [comment]
Test steps:
- Go to /agents/settings page
- Click the title `Idle Timeout` then it should work like toggle button..
- Only group titles and feature titles should be bold.
- Styles should look like design.
test

**Comment by richardhealy** [comment]
Waiting for https://github.com/deskpro/deskpro-admin-frontend/pull/248 to be finished before I check this, as I think it's important to check it with this branch.

**Comment by pxzdev** [comment]
new styles applied, review it

**Comment by pxzdev** [comment]
we dont need this PR anymore, I copied changes to 250 PR

**Pull request closed without merging**
