### PR TITLE
Implemented validation for auth & sso page

### PR DESCRIPTION
**Pull request by yegor92**
Settings Page: Agent Auth & SSO Validation
We need to add validation schema and error messages to this page

http://localhost:3000/#/agents/auth/settings

### CODE REVIEW

**Comment by richardhealy** [comment]
Just need to raise coverage

**Comment by richardhealy** [comment]
Also, in master, there is a bunch of typing issues that have been fixed. Could you merge master into this branch and let me know.

**Comment by richardhealy** [comment]
When the main switch on the feature is turned off (as in, everything is hidden), then it shouldn't validate:

Repo steps:

- Turn off main switch on feature
- Press save
- Turn on main switch (to show everything)
- See validation has been run and showing error messages.

**Comment by yegor92** [comment]
> When the main switch on the feature is turned off (as in, everything is hidden), then it shouldn't validate:
> 
> Repo steps:
> 
> * Turn off main switch on feature
> * Press save
> * Turn on main switch (to show everything)
> * See validation has been run and showing error messages.

Updated and pushed.

**Pull request merged**
