### PR TITLE
feature/7092-string-list-builder

### PR DESCRIPTION
**Pull request by pxzdev**
Add string list builder component

### CODE REVIEW

**Comment by richardhealy** [comment]
Storybook I get this error: 
Screenshot 2020-01-17 at 08 02 01

**Comment by richardhealy** [comment]
The pop input needs to change in the branch. I will we need to use something similar to this:

http://localhost:9009/?path=/story/table-data--inline-edit-1-input

Clicking "Add" adds one more value to the edit of the row. If you click it, you should be able to edit it (currently it deletes). when some presses enter, it switches back to non-edit mode.

**Comment by pxzdev** [comment]
@richardhealy I added inline input for both variants of StringListBuilder

**Comment by richardhealy** [comment]
Spotted 3 issues:

1. I know that it wasn't originally specified, but clicking outside of the inline edit (when it has a value should commit the value to the list also.
2. If the inline edit has not value, it should delete the value (as no point having an empty value).
3. Clicking the item deletes it. It should edit the item. (unless the delete icon is pressed).

**Pull request merged**
