### PR TITLE
fix/8024-table-boolean-filters

### PR DESCRIPTION
**Pull request by pxzdev**
Allow `YES_NO` operator to handle `BOOL` filters

Issue:
image

Steps to review:
 * Open agents table page
 * Click on `Filter` button at `TableActions`
 * Select `admin_common.col.can_admin` property and `Yes` as item
 * Click `Apply filter` button
 * Check filtered table

### CODE REVIEW

**Comment by richardhealy** [comment]
Reopening the filters panel shows a textbox with the 'yes' / 'no' value. It should be the original dropdown.

Screenshot 2020-01-23 at 17 09 09

**Comment by richardhealy** [comment]
@pxzdev https://github.com/deskpro/deskpro-admin-frontend/pull/215#issuecomment-577591358 still doesn't look fixed when I pulled the branch.

**Comment by pxzdev** [comment]
@richardhealy just tried, it work fine for me. Could you ensure that after pulling you have this lines:
https://github.com/deskpro/deskpro-admin-frontend/pull/215/files#diff-dfc07f8d10019c17de9e9cb8648d777fR114

Peek 2020-01-27 06-57

**Comment by richardhealy** [comment]
II see the dropdown now

I'm seeing this error in your branch, but not in master?

https://www.dropbox.com/s/9d7ub1ram20mbm7/AwesomeScreenshot-2020-1-27-1580098218936.webm?dl=0

**Comment by pxzdev** [comment]
I have the same issue in master too. It's not BOOL issue, it's `CONTAINS` filter type issue. Should I fix it in this PR?

**Comment by richardhealy** [comment]
> I have the same issue in master too. It's not BOOL issue, it's `CONTAINS` filter type issue. Should I fix it in this PR?

If the bug is in master, then that's okay. Merge this in. As for the bug, what should happen is we create a bug ticket and add that to the Iteration. (If we have space, which it looks like we do.) Could you create a ticket for it and let me know the ticket number?

**Comment by pxzdev** [comment]
@richardhealy unfortunately, it seems like I have no rights to view and make new issues

**Comment by pxzdev** [comment]
ok, created one

**Pull request merged**
